=== Juty4/1DAW-LdM/RA1/CreacionYValidacionXML/furgonetas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Empresas_alquiler_furgonetas">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="clientes" type="Tclientes" />
                <xs:element name="furgonetas_disponibles" type="Tfurgonetas_disponibles"/>
                <xs:element name="registro_solicitudes" type="Tregistro_solicitudes"/>
                <xs:element name="servicios_especiales" type="Tservicios_especiales"/>
            </xs:sequence>
        </xs:complexType>
    <!-- Keys -->

        <xs:key name="pk_cliente">
            <xs:selector xpath=".//cliente"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="pk_vehiculo">
            <xs:selector xpath=".//vehiculo"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="pk_servicio">
            <xs:selector xpath=".//servicio"/>
            <xs:field xpath="@id"/>
        </xs:key>


        <xs:keyref name="fk_cliente" refer="pk_cliente">
            <xs:selector xpath=".//solicitud"/>
            <xs:field xpath="@cliente"/>
        </xs:keyref>

        <xs:keyref name="fk_vehiculo" refer="pk_vehiculo">
            <xs:selector xpath=".//solicitud"/>
            <xs:field xpath="@vehiculo"/>
        </xs:keyref>

        <xs:keyref name="fk_servicio" refer="pk_servicio">
            <xs:selector xpath=".//solicitud"/>
            <xs:field xpath="@servicio_especial"/>
        </xs:keyref>

    </xs:element>

    <!-- ComplexType primera parte-->
<xs:complexType name="Tclientes">
    <xs:sequence>
        <xs:element name="cliente" type="Tcliente" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="Tfurgonetas_disponibles">
    <xs:sequence>
        <xs:element name="furgoneta_categorias" type="Tfurgoneta_categorias"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="Tregistro_solicitudes">
    <xs:sequence>
        <xs:element name="solicitud" type="Tsolicitud" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="Tservicios_especiales">
    <xs:sequence>
        <xs:element name="servicio" type="Tservicio" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

    <!-- ComplexType segunda parte-->
        
<xs:complexType name="Tcliente">
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="nombre" type="xs:string"/>
    <xs:attribute name="apellidos" type="xs:string"/>
    <xs:attribute name="direccion" type="xs:string"/>
    <xs:attribute name="telefono" type="xs:string"/>
    <xs:attribute name="dni" type="xs:string" use="optional"/>
</xs:complexType>

<xs:complexType name="Tfurgoneta_categorias">
    <xs:sequence>
        <xs:element name="categoria" type="Tcategoria" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="Tcategoria">
    <xs:sequence>
        <xs:element name="vehiculo" type="Tvehiculo" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="tipo" type="xs:string"/>
</xs:complexType>

<xs:complexType name="Tsolicitud" mixed="true">
    <xs:attribute name="cliente" type="xs:IDREF"/>
    <xs:attribute name="vehiculo" type="xs:IDREF"/>
    <xs:attribute name="fecha_recogida" type="xs:date"/>
    <xs:attribute name="hora_recogida" type="xs:string"/>
    <xs:attribute name="fecha_devolucion" type="xs:date"/>
    <xs:attribute name="hora_devolucion" type="xs:string"/>
    <xs:attribute name="servicio_especial" type="xs:IDREF" use="optional"/>
</xs:complexType>

<xs:complexType name="Tservicio">
    <xs:attribute name="id" type="xs:ID"></xs:attribute>
    <xs:attribute name="nombre_servicio" type="xs:string"></xs:attribute>
    <xs:attribute name="precio_servicio" type="xs:string"></xs:attribute>
</xs:complexType>

<xs:complexType name="Tvehiculo">
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="plazas" type="xs:string"/>
    <xs:attribute name="marca" type="xs:string"/>
    <xs:attribute name="modelo" type="xs:string"/>
</xs:complexType>

    <!-- SimpleType -->


</xs:schema>

=== Juty4/1DAW-LdM/RA1/CreacionYValidacionXML/furgonetas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- SECCIÓN CLIENTES-->
<Empresas_alquiler_furgonetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="furgonetas.xsd">
    
<clientes>
    <cliente id="CL001" nombre="carmen" apellidos="" direccion="" telefono="" dni=""></cliente>
    <cliente id="CL002" nombre="carlos" apellidos="" direccion="" telefono="" dni=""></cliente>
    <cliente id="CL003" nombre="ana" apellidos="" direccion="" telefono="" dni=""></cliente>
    <cliente id="CL004" nombre="lucia" apellidos="" direccion="" telefono="" dni=""></cliente>
    
</clientes>
<!-- SECCIÓN FURGONETAS DISPONIBLES-->
 <furgonetas_disponibles>
    <furgoneta_categorias>
        <categoria tipo="mini">
            <vehiculo id="M001" plazas="" marca="" modelo="" ></vehiculo>
            <vehiculo id="M002" plazas="" marca="" modelo="" ></vehiculo>

        </categoria>
        <categoria tipo="compact">
            <vehiculo id="C001" plazas="" marca="" modelo="" ></vehiculo>
            <vehiculo id="C002" plazas="" marca="" modelo="" ></vehiculo>

        </categoria>
        <categoria tipo="grand">
            <vehiculo id="G001" plazas="" marca="" modelo="" ></vehiculo>
            <vehiculo id="G002" plazas="" marca="" modelo="" ></vehiculo>

        </categoria>
        <categoria tipo="xlarge">
            <vehiculo id="XL001" plazas="" marca="" modelo="" ></vehiculo>
            <vehiculo id="XL002" plazas="" marca="" modelo="" ></vehiculo>

        </categoria>
    </furgoneta_categorias>
 </furgonetas_disponibles>
<!-- SECCIÓN REGISTRO DE SOLICITUDES-->
 <registro_solicitudes>
    <solicitud cliente="CL002" vehiculo="XL002" fecha_recogida="2026-03-15" hora_recogida="09:00" fecha_devolucion="2026-03-18" hora_devolucion="18:00" servicio_especial="SE001">La furgoneta tuvo una avería y ha sido recientemente reparada</solicitud>
    <solicitud cliente="CL004" vehiculo="G002" fecha_recogida="2026-03-20" hora_recogida="10:30" fecha_devolucion="2026-03-22" hora_devolucion="17:00" servicio_especial="SE002"></solicitud>
    <solicitud cliente="CL001" vehiculo="M001" fecha_recogida="2026-04-01" hora_recogida="08:00" fecha_devolucion="2026-04-03" hora_devolucion="20:00" servicio_especial="SE003"></solicitud>
</registro_solicitudes>
<!-- SECCIÓN SERVICIOS ESPECIALES QUE PUEDEN SER 0, 1 O MÁS-->
<servicios_especiales>
    <servicio id="SE001" nombre_servicio="sillita bebe" precio_servicio="75€"/>
    <servicio id="SE002" nombre_servicio="Depósito lleno en origen" precio_servicio="150€"/>
    <servicio id="SE003" nombre_servicio="portabicicletas exterior" precio_servicio="50€"/>
</servicios_especiales>

</Empresas_alquiler_furgonetas>
