=== Juty4/1DAW-LdM/RA4/solucion Actividad 3 dtd/LMSGI04-A3.dtd
<!ELEMENT almacen (productos,ubicaciones,palets?)>

<!ELEMENT productos (producto+)>

<!ELEMENT producto EMPTY>
	<!ATTLIST producto id ID #REQUIRED>
	<!ATTLIST producto descripcion CDATA #REQUIRED>
	<!ATTLIST producto valor_ud CDATA #IMPLIED>
	<!ATTLIST producto unidades CDATA #REQUIRED>

<!ELEMENT ubicaciones (nave+)>

<!ELEMENT nave (sector*)>
	<!ATTLIST nave id ID #REQUIRED>

<!ELEMENT sector (#PCDATA)>
	<!ATTLIST sector id ID #REQUIRED>
	<!ATTLIST sector estado CDATA #REQUIRED>
	<!ATTLIST sector capacidad CDATA #IMPLIED>

<!ELEMENT palets (palet*)>

<!ELEMENT palet (contenido*,observaciones?)>
	<!ATTLIST palet id ID #REQUIRED>
	<!ATTLIST palet ubicacion IDREF #IMPLIED>
	<!ATTLIST palet verificado CDATA #IMPLIED>

<!ELEMENT contenido EMPTY>
	<!ATTLIST contenido producto IDREF #REQUIRED>
	<!ATTLIST contenido cantidad CDATA #REQUIRED>

<!ELEMENT observaciones (#PCDATA)>

=== Juty4/1DAW-LdM/RA4/solucion Actividad 3 dtd/LMSGI04-A3 - dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE almacen SYSTEM "LMSGI04-A3.dtd">
<almacen>
	<productos>
		<producto id="GS001" descripcion="Golosina tipo 1" valor_ud="1.30" unidades="cajas"/>
		<producto id="PR001" descripcion="Piruleta tipo 1" valor_ud="1.50" unidades="cajas"/>
		<producto id="PS001" descripcion="Pistacho tipo 1" valor_ud="3.25" unidades="bolsas"/>
	</productos>
	<ubicaciones>
		<nave id="NV001">
			<sector id="SC001001" estado="D" capacidad="3000" />
			<sector id="SC001002" estado="D" capacidad="2000" />
		</nave>
		<nave id="NV0002">
			<sector id="SC002001" estado="D" capacidad="2500" />
			<sector id="SC002002" estado="N">
				En obras por reparaciones varias.
			</sector>
		</nave>
	</ubicaciones>
	<palets>
		<palet id="PL000001" ubicacion="SC001001" verificado="2019-01-15T17:45:00">
			<contenido producto="PS001" cantidad="400"/>
			<observaciones>Presenta rotura en una de las bolsas</observaciones>
		</palet>
		<palet id="PL000002">
			<contenido producto="GS001" cantidad="40"/>
			<contenido producto="PR001" cantidad="60"/>
		</palet>
	</palets>
</almacen>
