=== Juty4/1DAW-LdM/RA4/XSD/01-marcadoresmodular.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="marcadores">
	  <xs:complexType>
	     <xs:sequence   maxOccurs="unbounded">
		 	<xs:element name="pagina" type="tpagina"/>
		 </xs:sequence>
	  </xs:complexType>	
	</xs:element>
<!-- Tipos compuestos -->
<xs:complexType name="tpagina">
	<xs:all>
	  <xs:element ref="nombre" />
	  <xs:element name="descripcion" type="xs:string"/>
	  <xs:element name="url" type="xs:string"/>
	</xs:all>
</xs:complexType>
<xs:element name="nombre">
<xs:complexType mixed="true"> 
  <xs:attribute name="edad" type="xs:positiveInteger"/>
</xs:complexType>
</xs:element>


</xs:schema>

=== Juty4/1DAW-LdM/RA4/XSD/01-ejemplo-de-uso.xml
<?xml version="1.0" encoding="UTF-8"?>
<marcadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="01-marcadoresmodular.xsd">
	 <pagina>
		 <nombre edad='3'>Xataka</nombre>
		 <descripcion>Noticias sobre tecnología.</descripcion>
		 <url>https://www.xataka.com/</url>
	 </pagina>
	 <pagina>
		 <nombre>Wikipedia</nombre>
		 <descripcion>La enciclopedia libre.</descripcion>
		 <url>http://www.wikipedia.org/</url>
	 </pagina>
	 <pagina>
	 
		 <nombre>W3C</nombre>
		 <descripcion>World Wide Web Consortium.</descripcion>
		 
		 <url>http://www.w3.org/</url>
	 </pagina>
</marcadores>
